config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :menu_items
  resources :menu_categories
  resources :order_items
  resources :orders
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'payment/:order_id/new' => 'payments#new', as: 
  :checkout

end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
	has_many :menu_items
end

app/controllers/menu_categories_controller.rb
class MenuCategoriesController < ApplicationController
  before_action :set_menu_category, only: [:show, :edit, :update, :destroy]

  # GET /menu_categories
  # GET /menu_categories.json
  def index
    @menu_categories = MenuCategory.all
  end

  # GET /menu_categories/1
  # GET /menu_categories/1.json
  def show
  	@menu_items = MenuItem.all
  end

  # GET /menu_categories/new
  def new
    @menu_category = MenuCategory.new
  end

  # GET /menu_categories/1/edit
  def edit
  end

  # POST /menu_categories
  # POST /menu_categories.json
  def create
    @menu_category = MenuCategory.new(menu_category_params)

    respond_to do |format|
      if @menu_category.save
        format.html { redirect_to @menu_category, notice: 'Menu category was successfully created.' }
        format.json { render :show, status: :created, location: @menu_category }
      else
        format.html { render :new }
        format.json { render json: @menu_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_categories/1
  # PATCH/PUT /menu_categories/1.json
  def update
    respond_to do |format|
      if @menu_category.update(menu_category_params)
        format.html { redirect_to @menu_category, notice: 'Menu category was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_category }
      else
        format.html { render :edit }
        format.json { render json: @menu_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_categories/1
  # DELETE /menu_categories/1.json
  def destroy
    @menu_category.destroy
    respond_to do |format|
      format.html { redirect_to menu_categories_url, notice: 'Menu category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_category
      @menu_category = MenuCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_category_params
      params.require(:menu_category).permit(:name, :menu_item_id)
    end
end

app/helpers/menu_categories_helper.rb
module MenuCategoriesHelper
end

app/views/menu_categories/_form.html.erb
<%= form_with(model: menu_category, local: true) do |form| %>
  <% if menu_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_category.errors.count, "error") %> prohibited this menu_category from being saved:</h2>

      <ul>
      <% menu_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :menu_category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_categories/edit.html.erb
<h1>Editing Menu Category</h1>

<%= render 'form', menu_category: @menu_category %>

<%= link_to 'Show', @menu_category %> |
<%= link_to 'Back', menu_categories_path %>

app/views/menu_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Categories</h1>

<table class="table-light table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_categories.each do |menu_category| %>
      <tr>
        <td><%= menu_category.name %></td>
        <td><%= link_to 'Show', menu_category %></td>
        <td><%= link_to 'Edit', edit_menu_category_path(menu_category) %></td>
        <td><%= link_to 'Destroy', menu_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Category', new_menu_category_path %>

app/views/menu_categories/new.html.erb
<h1>New Menu Category</h1>

<%= render 'form', menu_category: @menu_category %>

<%= link_to 'Back', menu_categories_path %>

app/views/menu_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu_category.name %>
</p>

<% @menu_category.menu_items.all.each do |m| %>
	<%= m.name %> <br />
<% end %>

<%= link_to 'Edit', edit_menu_category_path(@menu_category) %> |
<%= link_to 'Back', menu_categories_path %>