config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :menu_items
  resources :menu_categories
  resources :order_items
  resources :orders
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'payment/:order_id/new' => 'payments#new', as: 
  :checkout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Farbucks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Farbucks</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
	  
		<%= link_to("Home", page_path("home"), :class => "nav-link") %>
		
      </li>
	  <li class="nav-item">
	  
		<%= link_to("Locations", locations_path, :class => "nav-link") %>
		
      </li>
      <li class="nav-item">
        
		<%= link_to("Menu Categories", menu_categories_path, :class => "nav-link") %>
		
      </li>
	        <li class="nav-item">
        
		<%= link_to("Menu Items", menu_items_path, :class => "nav-link") %>
		
      </li>
	  <li class="nav-item">
	  
		<%= link_to("Order", orders_path, :class => "nav-link") %>
		
      </li>
    </ul>
  </div>
</nav>
  
    <%= yield %>
  </body>
</html>